---
# tasks file for bind

- name: Install required packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - bind
    - bind-utils
  notify: restart named

- name: update configuration
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
    backup: yes
  notify: restart named

- name: Start services
  service:
    name: named
    state: started
    enabled: True


