---
# tasks file for bind

- name: Install required packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - bind
    - bind-utils
  notify: restart named

- name: update configuration
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
  notify: reload named

- name: Allow bind to write to master zone files
  seboolean:
    name: named_write_master_zones
    state: yes
    persistent: yes

- name: Make sure bind can pass through firewall
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item }} service name=dns accept"
    permanent: true
    immediate: true
    zone: public
    state: enabled
  with_items: '{{ bind_firewall_permit }}'
  when: firewalld_enabled and bind_firewall_permit
  notify: reload firewalld
  tags:
    - security
    - firewall

- name: Make sure rndc can pass through firewall
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item[0] }} port port=953 protocol={{ item[1] }} accept"
    permanent: true
    immediate: true
    zone: public
    state: enabled
  with_nested:
    - '{{ rndc_firewall_permit }}'
    - [ udp, tcp ]
  when: firewalld_enabled and rndc_firewall_permit
  notify: reload firewalld
  tags:
    - security
    - firewall


- name: Start services
  service:
    name: named
    state: started
    enabled: True


