---
# tasks file for bind

- name: Install required packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - bind
    - bind-utils
  notify:
    - restart named
    - update aide
  tags:
    - bind
    - install

- name: update configuration
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
  notify:
    - reload named
    - update aide
  tags:
    - bind
    - config

- name: Allow bind to write to master zone files
  seboolean:
    name: named_write_master_zones
    state: yes
    persistent: yes
  notify: update aide
  tags:
    - bind
    - selinux

- name: Allow bind to write to /var/named
  file:
    name: /var/named
    state: directory
    mode: 0770
  when: bind_var_writable
  notify: update aide
  tags:
    - bind

- name: Make sure bind can pass through firewall
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item.source | default(item) }} service name=dns accept"
    permanent: true
    immediate: true
    zone: '{{ item.zone | default("public") }}'
    state: '{{ item.state | default("enabled") }}'
  with_items: '{{ bind_firewall_permit }}'
  when: firewalld_enabled and bind_firewall_permit
  notify:
    - reload firewalld
    - update aide
  tags:
    - security
    - firewall

- name: Make sure rndc can pass through firewall
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item[0].source | default(item[0]) }} port port=953 protocol={{ item[1] }} accept"
    permanent: true
    immediate: true
    zone: '{{ item[0].zone | default("public") }}'
    state: '{{ item[0].state | default("enabled") }}'
  with_nested:
    - '{{ rndc_firewall_permit }}'
    - [ udp, tcp ]
  when: firewalld_enabled and rndc_firewall_permit
  notify:
    - reload firewalld
    - update aide
  tags:
    - bind
    - security
    - firewall

- name: Start services
  service:
    name: named
    state: started
    enabled: True
  notify: update aide
  tags:
    - bind
    - service

