---
# tasks file for bind

- name: Install required packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - bind
    - bind-utils
  notify: restart named

- name: update configuration
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
  notify: restart named

- name: Allow bind to write to master zone files
  seboolean:
    name: named_write_master_zones
    state: yes
    persistent: yes

- name: Make sure services can pass through firewall
  firewalld:
    service: dns
    permanent: true
    immediate: true
    state: enabled
  when:
    - firewalld_state != 'stopped'
  notify:
    - reload firewalld
  tags:
    - security
    - firewall

- name: Start services
  service:
    name: named
    state: started
    enabled: True


